"""Values for filling in data"""

# Gender
gender = ["Male", "Female"]

# Age
age = range(12, 31)

# WASSCE Aggregate
wassce_aggregate = range(6, 55)

# BECE Aggregate
bece_aggregate = range(6, 55)

# Preferred Program and cut-off point
preferred_programs = {
    "BSc. Biological Sciences": 22,
    "BSc. Agriculture": 20,
    "BSc. Earth Sciences": 24,
    "BSc. Agricultural Engineering": 23,
    "BSc. Agricultural Engineering (Full-Feepaying)": 22,
    "BSc. Biomedical Engineering": 10,
    "BSc. Biomedical Engineering (Full-Feepaying)": 12,
    "BSc. Computer Engineering": 9,
    "BSc. Computer Engineering (Full-Feepaying)": 10,
    "BSc. Food Process Engineering": 18,
    "BSc. Food Process Engineering (Full-Feepaying)": 19,
    "BSc. Materials Science & Engineering": 17,
    "BSc. Materials Science & Engineering (Full-Feepaying)": 18,
    "BSc. Family & Child Studies": 16,
    "BSc. Food & Clothing": 20,
    "BSc. Information Technology": 12,
    "BSc. Information Technology (Full-Feepaying)": 14,
    "BSc. Mathematical Sciences": 19,
    "BSc. Mathematical Sciences (Full-Feepaying)": 24,
    "BSc. Physical Sciences": 24,
    "Doctor of Veterinary Medicine": 14,
    "BSc. Psychology": 20,
    "Bachelor of Medicine": 7,
    "Bachelor of Surgery": 7,
    "Doctor of Pharmacy": 8,
    "BSc. Nursing": 9,
    "BSc. Midwifery": 9,
    "Bachelor of Dental Surgery": 9,
    "BSc. Medical Laboratory Sciences": 11,
    "BSc. Physiotherapy": 14,
    "BSc. Nutrition & Dietetics": 14,
    "BSc. Diagnostic Radiography": 13,
    "BSc. Occupational Therapy": 18,
    "BSc. Respiratory Therapy": 16,
    "BSc. Education": 24,
    "BA. Education": 24,
    "B.Ed. (JHS Specialism)": 24,
    "BA. Education (English)": 24,
    "BA. Sports and Physical Culture": 24,
    "BSc. Information Technology - Distance Education": 24,
    "BSc. Administration - Distance Education": 30,
    "Bachelor of Arts - Distance Education": 30,
    "Bachelor of Laws": 7,
    "BSc. Administration - Legon Campus": 9,
    "BSc. Administration - Legon Campus (Full-Fee Paying)": 14,
    "BSc. Administration - City Campus": 24,
    "Bachelor of Arts (General Arts Background)": 16,
    "Bachelor of Arts Full-Fee Paying": 24,
    "Bachelor of Arts (Business/Science/ Vocational Background)": 12,
    "Bachelor of Arts City Campus": 24,
    "Bachelor of Fine Arts": 22,
}

# Dream Job
dream_jobs = [
    "Software Engineering Manager",
    "Mobile Applications Developer",
    "Information Systems Security Manager",
    "Database Manager",
    "Data Security Analyst",
    "Product Manager",
    "Artificial Intelligence (AI) Engineer",
    "Full-Stack Developer",
    "Cloud Architect",
    "DevOps Engineer",
    "Blockchain Engineer",
    "Software Architect",
    "Big Data Engineer",
    "Internet of Things (IoT) Solutions Architect",
    "Data Scientist",
    "Cyber Security Engineer",
    "IT Systems Security Manager",
    "Applications Architect",
    "Data Architect",
    "Site Reliability Engineer",
    "Development Operations Manager",
    "IT Security Specialist",
    "Application Analyst",
    "User Interface Designer",
    "Application Developer",
    "Business Intelligence Analyst",
    "Software Test Engineer",
    "Information Technology Manager",
    "User Experience Designer",
    "Business Intelligence Developer",
    "Hardware Design Engineer",
    "Solutions Engineer",
    "Network Security Engineer",
    "Data Warehouse Architect",
    "Cloud Engineer",
    "Enterprise Architect",
    "Computer Programmer",
    "Computer Systems Analyst",
    "Network and Computer System Administrators",
    "Sales and marketing manager",
    "Hotel receptionist",
    "Cruise ship entertainer",
    "Head chef",
    "Tour guide",
    "Fitness instructor",
    "Concierge",
    "Cosmetologist",
    "Sommelier",
    "Casino host",
    "Travel agent",
    "Event manager",
    "Flight attendant",
    "Front of house manager",
    "Wedding planner",
    "Bartender",
    "Director of housekeeping",
    "Resident DJ",
    "Restaurant manager",
    "Hotel manager",
    "Parking lot attendant",
    "Maintenance worker",
    "Baggage porter",
    "Busser",
    "Theme Park manager",
    "Hair stylist",
    "Usher",
    "Barista",
    "Reservation agent",
    "Housekeeper",
    "Server",
    "Baker",
    "Retail sales associate",
    "Switchboard operator",
    "Apartment manager",
    "Actor",
    "Art critic",
    "Art director",
    "Art teacher",
    "Artist",
    "Choreographer",
    "Composer",
    "Costume designer",
    "Curator",
    "Dancer",
    "Director",
    "Event coordinator",
    "Graphic designer",
    "Illustrator",
    "Interior designer",
    "Lighting designer",
    "Make-up artist",
    "Musician",
    "Painter",
    "Photographer",
    "Poet",
    "Production assistant",
    "Production designer",
    "Scenic designer",
    "Sculptor",
    "Set decorator",
    "Sound designer",
    "Special effects artist",
    "Stage manager",
    "Storyboard artist",
    "Technical director",
    "Theater critic",
    "Theater manager",
    "Theater usher",
    "Video game designer",
    "Video producer",
    "Teacher",
    "Professor",
    "School counselor",
    "Librarian",
    "Special education teacher",
    "School administrator",
    "School principal",
    "Guidance counselor",
    "Curriculum specialist",
    "Admissions officer",
    "Educational researcher",
    "School psychologist",
    "Teacher assistant",
    "Online instructor",
    "Tutor",
    "School nurse",
    "Speech pathologist",
    "Adult education instructor",
    "ESL teacher",
    "Early childhood educator",
    "Child care center director",
    "Education policy analyst",
    "Education consultant",
    "Educational program coordinator",
    "Teacher trainer",
    "Education technology specialist",
    "Instructional designer",
    "Educational content writer",
    "Textbook editor",
    "Education journalist",
    "Education blogger",
    "Accountant",
    "Advertising Manager",
    "Brand Manager",
    "Business Development Manager",
    "Chief Executive Officer (CEO)",
    "Chief Financial Officer (CFO)",
    "Chief Operating Officer (COO)",
    "Consultant",
    "Data Analyst",
    "Entrepreneur",
    "Financial Analyst",
    "Human Resources Manager",
    "Information Technology (IT) Manager",
    "Investment Banker",
    "Management Analyst",
    "Market Research Analyst",
    "Marketing Manager",
    "Operations Manager",
    "Product Manager",
    "Project Manager",
    "Public Relations Manager",
    "Sales Manager",
    "Supply Chain Manager",
    "Tax Manager",
    "Bus driver",
    "Truck driver",
    "Delivery driver",
    "Taxi driver",
    "Chauffeur",
    "Pilot",
    "Flight engineer",
    "Flight attendant",
    "Air traffic controller",
    "Ship captain",
    "Ship navigator",
    "Deckhand",
    "Railroad conductor",
    "Locomotive engineer",
    "Subway operator",
    "Bicycle courier",
    "Motorcycle courier",
    "Garbage truck driver",
    "Postal worker",
    "Package handler",
    "Warehouse worker",
    "Forklift operator",
    "Dispatcher",
    "Freight broker",
    "Logistics coordinator",
    "Transportation manager",
    "Doctor",
    "Nurse",
    "Pharmacist",
    "Dentist",
    "Medical laboratory technician",
    "Radiologic technologist",
    "Physical therapist",
    "Occupational therapist",
    "Speech-language pathologist",
    "Dietitian",
    "Nutritionist",
    "Research scientist",
    "Biomedical engineer",
    "Clinical trial manager",
    "Clinical data analyst",
    "Medical writer",
    "Healthcare administrator",
    "Epidemiologist",
    "Public health analyst",
    "Environmental health and safety specialist",
    "Medical device sales representative",
    "Genetic counselor",
    "Psychologist",
    "Social worker",
    "Veterinarian",
    "Zoologist",
    "Ecologist",
    "Botanist",
    "Geologist",
    "Astronomer",
    "Physicist",
    "Chemist",
    "Mathematician",
    "Statistician",
    "Police officer",
    "Sheriff's deputy",
    "State trooper",
    "Detective",
    "Special agent",
    "Correctional officer",
    "Probation officer",
    "Parole officer",
    "Border patrol agent",
    "Customs and border protection officer",
    "Immigration and customs enforcement officer",
    "Firefighter",
    "Emergency medical technician",
    "Paramedic",
    "911 dispatcher",
    "Court clerk",
    "Court reporter",
    "Court interpreter",
    "Judicial law clerk",
    "Attorney",
    "Paralegal",
    "Legal assistant",
    "Judge",
    "Magistrate",
    "Public defender",
    "District attorney",
    "Criminal investigator",
    "Federal air marshal",
    "Secret Service agent",
    "Foreign service officer",
    "Intelligence analyst",
    "Diplomat",
    "Civil servant",
    "Military service member",
    "National park ranger",
    "Postal worker",
    "Census worker",
    "IRS agent",
    "Environmental protection specialist",
    "Occupational health and safety specialist",
    "Transportation security officer",
    "Journalist",
    "Reporter",
    "News Anchor",
    "Broadcast Technician",
    "Copywriter",
    "Public Relations Specialist",
    "Social Media Manager",
    "Digital Marketing Manager",
    "Advertising Account Executive",
    "Graphic Designer",
    "Web Developer",
    "Media Planner",
    "Media Buyer",
    "Market Research Analyst",
    "Brand Manager",
    "Content Strategist",
    "Copy Editor",
    "Video Producer",
    "Audio Engineer",
    "Photographer",
    "Comedian",
    "Magician",
    "Circus performer",
    "Stunt performer",
    "Screenwriter",
    "Film editor",
    "Film producer",
    "Talent agent",
    "Voice actor",
    "Radio host",
    "TV host",
    "Reality TV star",
    "Fashion designer",
    "Model",
    "Sports commentator",
    "Sports analyst",
    "Sports broadcaster"
]


# Favorite Subject 1, 2, 3
subjects = [
    "English Language",
    "Mathematics",
    "Integrated Science",
    "Social Studies",
    "Ghanaian Language",
    "French",
    "Spanish",
    "ICT",
    "Religious and Moral Education",
    "Physical Education",
    "Creative Arts",
    "Home Economics",
    "Agriculture Science",
    "Business Studies",
    "Geography",
    "History",
    "Government",
    "Economics",
    "Technical Drawing",
    "Music",
    "Biology",
    "Chemistry",
    "Physics",
    "Elective Mathematics",
    "Elective Physics",
    "Elective Chemistry",
    "Elective Biology",
    "General Knowledge in Art",
    "Visual Arts",
    "Dance",
    "Theater Arts"
]


# Interests(arts, business, engineering,etc)
interests = [
    "Arts",
    "Business",
    "Engineering",
    "Science",
    "Technology",
    "Mathematics",
    "History",
    "Politics",
    "Sports",
    "Music",
    "Literature",
    "Film",
    "Languages",
    "Cooking",
    "Travel",
    "Photography",
    "Gaming",
    "Fashion",
    "Fitness",
    "Social Media"
]


# Learning Style(visual, auditory, kinesthich)
learning_styles = [
    "Visual",
    "Auditory",
    "Kinesthetic",
    "Tactile",
    "Verbal",
    "Logical",
    "Social",
    "Solitary",
    "Naturalistic",
    "Musical",
    "Linguistic",
    "Spatial",
    "Reflective",
    "Global",
    "Analytical",
    "Intuitive",
    "Sequential",
    "Random"
]


# ExtraCurricular activities(sports, debate, code, etc)
extracurricular = [
    "Debate",
    "Theatre",
    "Art and Crafts",
    "Music",
    "Dance",
    "Sports",
    "Robotics",
    "Chess",
    "Photography",
    "Cooking",
    "Baking",
    "Gardening",
    "Volunteering",
    "Community Service",
    "Foreign Language Club",
    "Science Club",
    "Math Club",
    "Literary Club",
    "Environmental Club",
    "Astronomy Club"
]


# Native Language
native = [
    "Abron",
    "Acholi",
    "Adele",
    "Akuapem Twi",
    "Anufo",
    "Asante Twi",
    "Avatime",
    "Baoulé",
    "Bimoba",
    "Bissa",
    "Bono",
    "Buem",
    "Chakali",
    "Chala",
    "Dagaare",
    "Dagbani",
    "Dangme",
    "Ewe",
    "Fanti",
    "Frafra",
    "Ga",
    "Gonja",
    "Gurma",
    "Kasem",
    "Kusaal",
    "Kwahu Twi",
    "Larteh",
    "Lobi",
    "Logba",
    "Mampruli",
    "Nzema",
    "Safaliba",
    "Sekpele",
    "Sisaali",
    "Sontrokofi",
    "Tampulma",
    "Wale",
    "Wali",
    "Waale",
    "Wassa",
    "Wurche"
]


# Secondary Language
native = [
    "English",
    "French",
    "Arabic",
    "Portuguese",
    "Hindi",
    "Mandarin",
    "Spanish",
    "German",
    "Italian",
    "Dutch",
    "Swahili",
    "Russian",
    "Turkish",
    "Japanese",
    "Korean",
    "Fante",
    "Twi",
    "Ga",
    "Ewe",
    "Dagbani",
    "Hausa",
    "Gonja",
    "Dangme",
    "Nzema",
    "Bimoba",
    "Kusaal",
    "Kasem"
]


# Predicted Programme
